name: Zip repository and put on S3
on:
  push:
    branches: [ main ]

jobs:
  zip-n-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: <repository_name>

      - name: Zip Folder
        run: |
          zip -r <repository_name>.zip <repository_name> -x "<repository_name>/.git/*" "<repository_name>/.github/*"
