name: Zip repository and put on S3
on:
  push:
    branches: [ main ]

jobs:
  zip-n-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Zip Folder
        run: |
          zip -r repository.zip . -x "*.git/*" "*.github/*"

